name: CI

on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Compile Java Classes
        run: |
         cd P2
         ./gradlew build testClasses -x test
        
  TestPacManValidMoves:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          cd P2
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestPacManValidMoves
          
  TestPacManMove:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          cd P2
          /gradlew build testClasses -x test
          ./gradlew test --tests TestPacManMove
          
  TestGhostInRange:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          cd P2
          /gradlew build testClasses -x test
          ./gradlew test --tests TestGhostInRange
         
  TestConsume:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          cd P2
          /gradlew build testClasses -x test
          ./gradlew test --tests TestGhostInRange
          
  ghostValidMoves:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          cd Projects/P1
          /gradlew build testClasses -x test
          ./gradlew test --tests TestGhostValidMoves
          
  ghostMove:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          cd P2
          /gradlew build testClasses -x test
          ./gradlew test --tests TestGhostMove
          
  pacmanInRange:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          cd P2
          /gradlew build testClasses -x test
          ./gradlew test --tests TestPacManInRange
          
  attack:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          cd P2
          /gradlew build testClasses -x test
          ./gradlew test --tests TestAttack
          
  mapMove:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          cd P2
           /gradlew build testClasses -x test
          ./gradlew test --tests TestMapMove
  getLoc:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          cd P2
          /gradlew build testClasses -x test
          ./gradlew test --tests TestMapGetLoc
          
  eatCookie:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          cd P2
          /gradlew build testClasses -x test
          ./gradlew test --tests TestMapEatCookie
          
  mapAttack:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          cd P2
          /gradlew build testClasses -x test
          ./gradlew test --tests TestMapAttack
